Repository AY2223S2-CS2113-W15-3/tp, pull requests merged in 2023-03, with the labels that each got.

#34 Update UI to be used for display messages for each action
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/action/BudgetAction.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/test/java/seedu/duke/BudgetCommandTest.java
Labels: priority.High

#37 add help functions
  src/main/java/seedu/duke/action/BudgetAction.java
  src/main/java/seedu/duke/action/BudgetUIResponse.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandEnum.java
  src/main/java/seedu/duke/command/CommandParser.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/model/Budget.java
  src/main/java/seedu/duke/util/Messages.java
Labels: type.Enhancement

#62 Add assertion for command parsing, logging for file IO
  src/main/java/seedu/duke/Data.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandParser.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: priority.Low

#116 updated sequence diagram and class diagram according to comments
  docs/uml/BudgetCommand.puml
  docs/uml/BudgetCommandSequence.puml
Labels: type.Bug
